version: '3'

volumes:
    strategy_data:
        driver: local

services:
    strategy-backend:
        build:
            context: .
        ports:
            - "5000:5000"
        environment:
            HOST: mysql
            PORT: 3306
            USER: strategy
            PASSWORD: strategy
            DB: strategy_data
        networks:
            - default
    mysql:
        image: mysql:5.7
        ports:
            - "3306:3306"
        environment:
            MYSQL_USER: strategy
            MYSQL_PASSWORD: strategy
            MYSQL_ROOT_PASSWORD: strategy
            MYSQL_DATABASE: strategy_data
        volumes:
            - ./database:/docker-entrypoint-initdb.d
            - strategy_data:/var/lib/mysql
        networks:
            - default